const properties = [
  {
    id: 1,
    owner: 'Funmi Olaiya',
    status: 'Available',
    price: 'N2,000,000',
    purpose: 'Buy',
    duration: 'Nil',
    type: 'Duplex',
    bedroom: '3',
    bathroom: '3',
    state: 'Oyo',
    city: 'Ibadan',
    address: 'No.5, Are Road',
    created_on: 'November 25 2018',
    image_url: 'funmi111',
    isAdmin: 'NO',
  },
  {
    id: 2,
    owner: 'Seun Olaiya',
    status: 'Available',
    price: 'N1,000,000',
    purpose: 'Rent',
    duration: 'Monthly',
    type: 'Flat',
    bedroom: '2',
    bathroom: '3',
    state: 'Oyo',
    city: 'Ibadan',
    address: 'No.5, Bodija Road',
    created_on: 'November 25 2018',
    image_url: 'funmi111',
    isAdmin: 'NO',
  },
];
export default properties;