const Seed = {
  account: {
    email: 'funmijohn@hotmail.com',
    first_name: 'Funmilola',
    last_name: 'John',
    password: 'fuDd3457',
    phone_number: '08039873675',
    address: 'No. 4, Tade Ayade Close, New Bodija, Ibadan',
    is_admin: 'false',
  },

  noEmail: {
    email: '',
    first_name: 'Tade',
    last_name: 'Aderenle',
    password: 'TadeOgi8',
    phone_number: '08039867565',
    address: 'No. 4, Adesope Ileri Close, Lekki, Lagos',
    is_admin: 'false',
  },

  noFirstName: {
    email: 'TadeAde@gmail.com',
    first_name: '',
    last_name: 'Aderenle',
    password: 'TadeOgi8',
    phone_number: '08039867565',
    address: 'No. 4, Adesope Ileri Close, Lekki, Lagos',
    is_admin: 'false',
  },
  noLastName: {
    email: 'TadeAde@gmail.com',
    first_name: 'Tade',
    last_name: '',
    password: 'TadeOgi8',
    phone_number: '08039867565',
    address: 'No. 4, Adesope Ileri Close, Lekki, Lagos',
    is_admin: 'false',
  },
  noPassword: {
    email: 'TadeAde@gmail.com',
    first_name: 'Tade',
    last_name: 'Aderenle',
    password: '',
    phone_number: '08039867565',
    address: 'No. 4, Adesope Ileri Close, Lekki, Lagos',
    is_admin: 'false',
  },
  noPhoneNumber: {
    email: 'TadeAde@gmail.com',
    first_name: 'Tade',
    last_name: 'Aderenle',
    password: 'TadeOgi8',
    phone_number: '',
    address: 'No. 4, Adesope Ileri Close, Lekki, Lagos',
    is_admin: 'false',
  },
  noAddress: {
    email: 'TadeAde@gmail.com',
    first_name: 'Tade',
    last_name: 'Aderenle',
    password: 'TadeOgi8',
    phone_number: '08039867565',
    address: '',
    is_admin: 'false',
  },
  noIsAdmin: {
    email: 'TadeAde@gmail.com',
    first_name: 'Tade',
    last_name: 'Aderenle',
    password: 'TadeOgi8',
    phone_number: '08039867565',
    address: 'No. 4, Adesope Ileri Close, Lekki, Lagos',
    is_admin: '',
  },
  invalidEmail: {
    email: 'TadeAdegmail.com',
    first_name: 'Tade',
    last_name: 'Aderenle',
    password: 'TadeOgi8',
    phone_number: '08039867565',
    address: 'No. 4, Adesope Ileri Close, Lekki, Lagos',
    is_admin: 'false',
  },
  noValidNames: {
    email: 'TadeAde@gmail.com',
    first_name: 'Tad5',
    last_name: 'Aderenle7',
    password: 'TadeOgi8',
    phone_number: '08039867565',
    address: 'No. 4, Adesope Ileri Close, Lekki, Lagos',
    is_admin: 'false',
  },
  noValidNumber: {
    email: 'TadeAde@gmail.com',
    first_name: 'Tade',
    last_name: 'Aderenle',
    password: 'TadeOgi8',
    phone_number: '08039867565r',
    address: 'No. 4, Adesope Ileri Close, Lekki, Lagos',
    is_admin: 'false',
  },
  noValidPassword: {
    email: 'TadeAde@gmail.com',
    first_name: 'Tade',
    last_name: 'Aderenle',
    password: 'TadeOgi8yy',
    phone_number: '08039867565',
    address: 'No. 4, Adesope Ileri Close, Lekki, Lagos',
    is_admin: 'false',
  },
};

export default Seed;
